version: 2
jobs:
  build:
    docker:
      - image: vinodsharma/python:2.7-devel

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: Configure Docker Image Env Variable
          command: |
            echo 'export DOCKER_IMAGE=vinodsharma/circleci-demo-docker:$CIRCLE_SHA1' >> $BASH_ENV

      - run:
          name: Building Thestral Image
          command: |
            docker build -t  $DOCKER_IMAGE .

      - run:
          name: Running Tests
          command: |
            python tests/test_*.py

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE

      - deploy:
          name: Deploying to Prod if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws configure set default.region us-west-2
              aws configure set default.output json
              python deploy.py
            fi

      - deploy:
          name: Deploying to staging if tests pass and branch is not Master
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              aws configure set default.region us-east-1
              aws configure set default.output json
              python deploy.py
            fi
