
version: 2
jobs:
  build:
    docker:
      - image: vinodsharma/python:2.7-devel   # (1)
    working_directory: /opt/
    steps:

      - checkout

      - setup_remote_docker   # (2)

      # build and push Docker image
      - run: |
          name: Building Thestral Image
          docker build -t   vinodsharma/circleci-demo-docker:$CIRCLE_SHA1 .      # (3)


      - deploy:
          name: Deploying to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      # (4)
              docker push vinodsharma/circleci-demo-docker:$CIRCLE_SHA1
            fi
            # docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      # (4)
            # docker push vinodsharma/circleci-demo-docker:$CIRCLE_SHA1
