version: 2
jobs:
  build:
    docker:
      - image: vinodsharma/python:2.7-devel
    working_directory: /opt/
    steps:
      - checkout

      - setup_remote_docker

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   vinodsharma/circleci-demo-docker:$TAG

      - run:
          name: run tests
          command: |
            python tests/test_*.py

      - deploy:
          name: Deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push vinodsharma/circleci-demo-docker:$TAG
            fi
