version: 2
jobs:
  build:
    docker:
      - image: vinodsharma/python:2.7-devel   # (1)
    # working_directory: /opt/
    steps:

      - checkout

      - setup_remote_docker   # (2)

      - run:
          name: Configure Docker Image Env Varible
          command: |
            echo 'export DOCKER_IMAGE=vinodsharma/circleci-demo-docker:$CIRCLE_SHA1' >> $BASH_ENV

      - run:
          name: Building Thestral Image
          command: |
            docker build -t  $DOCKER_IMAGE .

      - run:
          name: Running Tests
          command: |
            python tests/test_*.py
