version: 2
jobs:
  build:
    docker:
      - image: vinodsharma/python:2.7-devel   # (1)
    # working_directory: /opt/
    steps:

      - checkout

      - setup_remote_docker   # (2)

      - run: echo 'export DOCKER_IMAGE=vinodsharma/circleci-demo-docker:$CIRCLE_SHA1' >> $BASH_ENV
      - run:
          name: Building Thestral Image
          command: |
            # docker build -t   vinodsharma/circleci-demo-docker:$CIRCLE_SHA1 .
            docker build -t  $DOCKER_IMAGE .
      - run:
          name: Running Tests
          command: |
            python tests/test_*.py
      - deploy:
          name: Deploying to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
	            aws configure set default.region us-west-2
            	aws configure set default.output json
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              # docker push vinodsharma/circleci-demo-docker:$CIRCLE_SHA1
              docker push $DOCKER_IMAGE
              python deploy.py
            fi
